### ISSUE TITLE
How to handle external packages needed for specific search methods?

### ISSUE THREAD

**Issue by THinnerichs** [Herb-AI/HerbSearch.jl#129]
With more and more added functionality, we add more and more packages to `HerbSearch` that are specific to a specific search method. E.g. `grammar_optimizer` loads `Clingo_jll`. You will probably not need `Clingo` when running the simple getting started guide or only probabilistic searches. The number of packages quickly accumulates. 

We should find a way to load those lazily when actually needed without making the entire system slower.

**Comment by ReubenJ** [comment]
[Package Extensions](https://docs.julialang.org/en/v1/manual/code-loading/#man-extensions) offer one approach. We'd just need to bump the minimum julia version to 1.9+

**Comment by THinnerichs** [comment]
As dependencies are rather small for now, I closed this issue.
